//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuraMiguelPerez
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SuraEntities : DbContext
    {
        public SuraEntities()
            : base("name=SuraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administradore> administradores { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<seguro> seguros { get; set; }
        public virtual DbSet<tipopago> tipopagoes { get; set; }
        public virtual DbSet<tiposeguro> tiposeguros { get; set; }
    }
}
