//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuraMiguelPerez
{
    using System;
    using System.Collections.Generic;
    
    public partial class seguro
    {
        public int id { get; set; }
        public int adicional { get; set; }
        public int tiposeguro_id { get; set; }
        public int tipopago_id { get; set; }
        public int cuotas { get; set; }
        public int cliente_id { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual tipopago tipopago { get; set; }
        public virtual tiposeguro tiposeguro { get; set; }
    }
}
